### ISSUE TITLE
Added the billing to the index.php but keep getting and error (embedded App)

### ISSUE THREAD

**Issue by reason8910** [stefanmomcilovic/Shopify-Generating-Api-Token#1]
array(4) {
  ["type"]=>
  int(8)
  ["message"]=>
  string(51) "Trying to access array offset on value of type null"
  ["file"]=>
  string(80) "/home/reasonco/public_html/app/apps/gat/controllers/billing/one_time_billing.php"
  ["line"]=>
  int(65)
}
[index.txt](https://github.com/stefanmomcilovic/Shopify-Generating-Api-Token/files/8203571/index.txt)

**Comment by reason8910** [comment]
Now when I return from billing i get a "Page not found" error.
Please can you tell me what setting to check.

**Comment by stefanmomcilovic** [comment]
Change GraphQL "returnUrl"
